name: Publish

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Do Clean
        run: ./gradlew clean

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set Version Name
        run: |
          sed -i '' 's/^VERSION_NAME=.*/VERSION_NAME=${{ env.RELEASE_VERSION }}/' gradle.properties
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}

      - name: 🚀 Publish Library to Maven Central
        if: always() && (github.event.inputs.should-publish == 'true')
        run: ./gradlew publish --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨Assemble
        if: always() && (github.event.inputs.should-publish == 'true')
        run: ./gradlew :mvicompose:assemble
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}

      - name: ⚙️ Create Release
        if: always() && (github.event.inputs.should-publish == 'true')
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${{ github.event.inputs.release-version }}" \
              --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.release-version }}
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}